language: rust
rust:
- nightly
cache: cargo
dist: trusty
sudo: required

env:
  global:
    - TARGET=x86_64-apple-darwin

install:
- git clone https://github.com/sstephenson/bats.git /tmp/bats && /tmp/bats/install.sh
  $HOME
script:
- cargo test --verbose
- "~/bin/bats --tap bats"
before_deploy:
- cargo build --release --target $TARGET
deploy:
- provider: releases
  api_key:
    secure: EADo7Tm91HzXlzMPV0KFamreJ68U/HceLzpv3jh8YyziPnznCnL7w6d4/YH+zxoA+PM1W94Z73orv084+RuWCUt9Ptcq8YYHWHfUmebmb8I0WjRKfxFPsyyHw8oTNYnmzuZiaVXn5OXFyB0XL6HNXrig46Ez0PQ6vm14ZnW1xCog0G0AoTQDgSb3m6j1BuDuJw6Bm6Q+YQtvoxuzVB8mhNN+l58jwuMHd/Uu8kyiRKtSaHiyLnSbz0+UdzOKbKtppdzFBtg2VvG2wWbw0U18D/pHLPaO6cwF4Jgvt0o0lzd83Fa46XL/5JcmZMkzh3Pr2HByYmesctq4FdptkHYORwqUqKxbnJDzQlumZMiI5pn34W6t9QW43OCFo7HV6O+DLGmk1NpNyLfY3Vn5b4nXTTCqOrEzt2iVBE5sqBG2Ke5Jd2o2hR/JIHcHzPfeDoEtihCnWz5qYu68KJojvcsdKwdYOhEpzezpG6SRXLWPVt68PiT8e/p33p0Y3zaQ4NCzxRHbjUuMNwRyiVWwP/dS4rfacFkVitri6DE+4JCMR/zyak4GaAWf3UmuTHh7cyafijfAj+/EVOoInQDI1vhM82wDRiYACkk9QgMxW+TLlbGU51c8X9IPBShqeGC94PwH3EZfwvNx8az5poyOHj0ZToX0iEceYBmHdpGjfBaMsDM=
  file: target/$TARGET/release/git-together
  skip_cleanup: true
  on:
    tags: true
