[package]
name = "git-together"
version = "0.1.0-alpha.7"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]

[dependencies]
error-chain = "0.5"
git2 = { git = "https://github.com/alexcrichton/git2-rs.git" }
