[package]
name = "git-together"
version = "0.1.0"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]

[dependencies]
error-chain = "0.5"

[dev-dependencies]
tempdir = "0.3"

[[test]]
name = "integration"
harness = false
